// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-jVCPJu5zfleeKz6caSochaghwCv3d1A',
    appId: '1:971511312576:web:ce0f241ac0dc617cc7bd25',
    messagingSenderId: '971511312576',
    projectId: 'cloudmsg-75d6a',
    authDomain: 'cloudmsg-75d6a.firebaseapp.com',
    storageBucket: 'cloudmsg-75d6a.firebasestorage.app',
    measurementId: 'G-GC537RT308',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5eUSewgaedEKG0ql_UnT9BB6dqjWvYck',
    appId: '1:971511312576:android:b64c1ef4f71541d9c7bd25',
    messagingSenderId: '971511312576',
    projectId: 'cloudmsg-75d6a',
    storageBucket: 'cloudmsg-75d6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBHpKMZpabWaKAsQAG6jaXN3A8gPLNZZs',
    appId: '1:971511312576:ios:a1924754939d3c60c7bd25',
    messagingSenderId: '971511312576',
    projectId: 'cloudmsg-75d6a',
    storageBucket: 'cloudmsg-75d6a.firebasestorage.app',
    iosBundleId: 'com.example.cloudmsg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBHpKMZpabWaKAsQAG6jaXN3A8gPLNZZs',
    appId: '1:971511312576:ios:a1924754939d3c60c7bd25',
    messagingSenderId: '971511312576',
    projectId: 'cloudmsg-75d6a',
    storageBucket: 'cloudmsg-75d6a.firebasestorage.app',
    iosBundleId: 'com.example.cloudmsg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-jVCPJu5zfleeKz6caSochaghwCv3d1A',
    appId: '1:971511312576:web:acef84b9cb09ef95c7bd25',
    messagingSenderId: '971511312576',
    projectId: 'cloudmsg-75d6a',
    authDomain: 'cloudmsg-75d6a.firebaseapp.com',
    storageBucket: 'cloudmsg-75d6a.firebasestorage.app',
    measurementId: 'G-6MW9S8FZRY',
  );
}
